spring:
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8443/uaa/.well-known/jwks.json'
  cloud:
    gateway:
      routes:
        - id: uua
          uri: lb://uaa
          predicates:
            - Path=/uaa/**
          filters:
            - StripPrefix=1

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.chenguoyu.cloud: debug
  file:
    max-size: 1GB